myapp/urls.py
from django.urls import path
from myapp import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls import url, include


app_name="myapp"

urlpatterns=[

    path(r'',views.Index.as_view(), name='index'),
    path('about/',views.about,name='about'),
    path(r'<int:book_id>/',views.Detail.as_view(), name='detail'),
    path(r'findbooks/',views.findbooks,name='findbooks'),
    path(r'place_order/',views.place_order,name='place_order'),
    path(r'review/',views.review,name='review'),
    path(r'user_login/',views.user_login,name='user_login'),
    path(r'user_logout/',views.user_logout,name='user_logout'),
    path(r'check_reviews/', views.chk_reviews, name='check_reviews'),
    path(r'check_reviews_done/<int:book_id>/',views.chk_reviews_done,name='check_reviews_done'),
    path(r'user_register/', views.user_register, name='user_register'),
    path(r'myorders/', views.myorders, name='myorders'),
    path(r'profile/',views.profile,name='profile'),
    path(r'media/',serve,{'document_root':settings.MEDIA_ROOT}),
    path('', include('django.contrib.auth.urls')),

    path('forgot_password/',views.forgot_password,name='forgot_password'),

    path('change_password/',views.change_password,name='change_password'),

]

mysiteF19/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path(r'myapp/', include('myapp.urls1')),
    path(r'myapp/',include('myapp.urls')),
    # path('accounts/login/',admin.site.urls),
    # path('', include('django.contrib.auth.urls'))

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from PIL import Image


class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country=models.CharField(max_length=200,default='USA')

    def __str__(self):
        return self.name


class Book(models.Model):
    CATEGORY_CHOICES = [
        ('S', 'Scinece&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]

    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='S')
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MaxValueValidator(1000), MinValueValidator(0)])
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.CASCADE)
    description=models.TextField(max_length=500, blank=True)
    num_reviews=models.PositiveIntegerField(default=0, validators=[MaxValueValidator(5), MinValueValidator(1)])

    def __str__(self):
        return self.title


class Member(User):
    STATUS_CHOICES = [
        (1, 'Regular member'),
        (2, 'Premium Member'),
        (3, 'Guest Member'),
    ]

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300, blank=True)
    city = models.CharField(max_length=20, default="Windsor")
    province=models.CharField(max_length=2, default='ON')
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True)
    # image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return self.username

    def get_borrowed_books(self):
        return " , ".join([b.title for b in self.borrowed_books.all()])
    get_borrowed_books.short_description = 'Borrowed Books'


class Order(models.Model):
    STATUS_CHOICES =[
        (0,'Purchase'),
        (1, 'Borrow')
    ]
    # id = models.AutoField(primary_key=True)
    books=models.ManyToManyField(Book)
    member= models.ForeignKey(Member, related_name='order', on_delete=models.CASCADE,blank=True, null=True)
    order_type=models.IntegerField(choices=STATUS_CHOICES,default=1)
    order_date=models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.id)

    def total_items(self):
        # return str(self.books)
        num_orders=self.books.count()
        return num_orders

    def book_list(self):
        books=self.books.all()
        print(books)


class Review(models.Model):
    reviewer=models.EmailField()
    book=models.ForeignKey(Book, on_delete=models.CASCADE)
    rating=models.PositiveIntegerField()
    comments=models.TextField(null=True, blank=True)
    date=models.DateField(default=timezone.now)

    def __str__(self):
        return str(self.reviewer)


class Profile(models.Model):
    user=models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self):
        super().save()
        img=Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size=(300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

myapp/forms.py
from django import forms
from myapp.models import Order, Review, Member, Profile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm
from django.contrib.auth.models import User


class SearchForm(forms.Form):
    CATEGORY_CHOICES=[
        ('S','Science&Tech'),
        ('F','Friction'),
        ('B','Biography'),
        ('T','Travel'),
        ('O','Other')
    ]
    # name=forms.CharField(max_length=100, required=False, label='Your Name')
    category=forms.ChoiceField(widget=forms.RadioSelect, choices=CATEGORY_CHOICES, required=False, label='Select a category')
    max_price=forms.IntegerField(label='Maximum Price', min_value=0)


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields=['books','order_type']
        widgets={'books':forms.CheckboxSelectMultiple(),
                 'order_type':forms.RadioSelect}
        labels={'member':'Member name'}


class ReviewForm(forms.ModelForm):
    class Meta:
        model=Review
        fields=['book','rating','comments']
        widgets={'book':forms.RadioSelect()}
        labels={'reviewer':'Please enter a valid email','rating':'Rating: An integer between 1(worst) and 5(best)'}


class RegisterForm(UserCreationForm):
    email=forms.EmailField()
    first_name = forms.CharField(max_length=100, required=False, label='First Name')
    last_name = forms.CharField(max_length=100, required=False, label='Last Name')

    class Meta:
        model=Member
        fields=['username','first_name','last_name','email','password1','password2']


class LoginForm(AuthenticationForm):
    class Meta:
        model=Member
        fields=['username','password']


class UserUpdateForm(forms.ModelForm):
    email=forms.EmailField()

    class Meta:
        model=Member
        fields=['username','email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['image']


class PasswordRequestForm(forms.ModelForm):
    email=forms.EmailField()
    last_name=forms.CharField()
    first_name=forms.CharField()

    class Meta:
        model=User
        fields=['first_name','last_name','email']


class PasswordChangeForm(SetPasswordForm):
     class Meta:
        model=Member
        fields=['password1','password2']

myapp/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Book, Review, Order, Member
from django.http import HttpResponse, HttpResponseRedirect
from .forms import SearchForm, OrderForm, ReviewForm, RegisterForm, LoginForm, UserUpdateForm, ProfileUpdateForm, PasswordRequestForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
import random, datetime, string
from django.contrib import messages
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import update_session_auth_hash


from django.core.mail import send_mail


class Index(View):

    def get(self, request):
        booklist=Book.objects.all().order_by('id')
        return render(request,'myapp/index.html',{'booklist':booklist})


def about(request):
    cookie_value=request.COOKIES.get('lucky_num')
    response = HttpResponse()
    if cookie_value is None:
        mynum = random.randint(1, 100)
    else:
        mynum = request.COOKIES['lucky_num']
    response= render(request,'myapp/about.html',{'mynum':mynum})
    response.set_cookie('lucky_num', mynum, expires=300)
    return response


class Detail(View):

    def get(self,request, book_id):
        book=get_object_or_404(Book,id=book_id)
        return render(request,'myapp/detail.html',{'book':book})


def findbooks(request):
    if request.method == 'POST':
        form= SearchForm(request.POST)
        if form.is_valid():
            category = form.cleaned_data['category']
            max_price = form.cleaned_data['max_price']
            if category:
                booklist = Book.objects.filter(category=category, price__lte=max_price)
            else:
                booklist=Book.objects.filter(price__lte=max_price)
            return render(request, 'myapp/results.html',{'booklist':booklist,'category':category})
        else:
            return HttpResponse('Invalid data')
    else:
        form=SearchForm()
        return render(request,'myapp/findbooks.html',{'form':form})


@login_required
def place_order(request):
    if request.method == 'POST':

        form = OrderForm(request.POST)

        if form.is_valid():
            books = form.cleaned_data['books']
            order = form.save()

            member_name = request.user.username

            o_type = order.order_type
            order.save()
            mem = Member.objects.get(username=member_name)

            if o_type == 1:
                for b in order.books.all():
                    mem.borrowed_books.add(b)

            return render(request, 'myapp/order_response.html', {'books': books, 'order': order})
        else:
            return render(request, 'myapp/placeorder.html', {'form': form})

    else:
        form=OrderForm()
        return render(request, 'myapp/placeorder.html', {'form':form})


@login_required
def review(request):
    username=request.user.username

    member_status = Member.objects.filter(username=username).values('status')
    if member_status[0]['status'] == 1 or member_status[0]['status'] == 2:

        if request.method=='POST':

            form=ReviewForm(request.POST)

            if form.is_valid():
                rating=form.cleaned_data['rating']

                review = form.save()
                review.reviewer = request.user.email
                book=review.book
                if rating in range(1,6):
                    review.save()
                    book_update=Book.objects.get(title=book)
                    book_update.num_reviews += 1
                    book_update.save()

                    booklist = Book.objects.all().order_by('id')
                    messages.success(request,'Your review is submitted!')
                    return render(request,'myapp/index.html',{'booklist':booklist})
                else:
                    form = ReviewForm()
                    return render(request, 'myapp/review.html', {'form':form, 'error': 'You must enter a rating between 1 and 5!'})
            else:
                return render(request,'myapp/review.html',{'form':form})

        else:
            form=ReviewForm()
            return render(request, 'myapp/review.html', {'form':form, 'error': ''})
    else:
        return render(request, 'myapp/review.html',
                      {'error': 'You are not able to submit the review!'})


def user_login(request):
    if 'username' not in request.session:

        if request.method=='POST':
            form = LoginForm(request.POST)

            username = request.POST['username']
            # password = form.cleaned_data.get('passsword')
            password = request.POST['password']
            user = authenticate(username=username, password=password)

            if user and user.is_active:
                login(request,user)
                request.session['username'] = username
                now = datetime.datetime.now()
                request.session['last_login']=now.strftime("%d-%m-%Y %H:%M:%S")
                request.session.set_expiry(60*5)
                messages.success(request, 'You are successfully Logged In!')

                if 'next' in request.POST:
                    return redirect(request.POST.get('next'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
                    # return render(request, 'myapp/index.html')
            else:
                messages.error(request,'Invalid data. Try again!')
                return render(request, 'myapp/login.html', {'form':form})
        else:
            form = LoginForm()
            return render(request,'myapp/login.html',{'form':form})

    else:
        booklist = Book.objects.all().order_by('id')
        return render(request, 'myapp/index.html', {'booklist': booklist})


@login_required
def user_logout(request):
    logout(request)
    return render(request, 'myapp/logout.html')
    # del request.session['username']


@login_required
def chk_reviews(request):
    booklist = Book.objects.all().order_by('id')
    return render(request, 'myapp/chk_reviews.html', {'booklist':booklist})


@login_required
def chk_reviews_done(request,book_id):

    member=Member.objects.filter(username=request.user)
    avg = 0
    if member:
        book=Review.objects.filter(book__id=book_id).values_list('rating',flat=True)

        if len(book)>0:
            avg=sum(book)/len(book)

        return render(request,'myapp/chk_reviews_done.html',{'avg':avg,'member':member})
    else:
        form = LoginForm()
        return render(request,'myapp/login.html',{'form':form})


def user_register(request):

    if request.method=='POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request, 'Account created for '+username)

            return render(request, 'myapp/index.html')
    else:
        form = RegisterForm()
    return render(request, 'myapp/register.html', {'form': form})


@login_required
def myorders(request):
    username = request.user.username
    member = Member.objects.filter(username=username)

    if member:
        order_list=Member.objects.filter(borrowed_books__title__startswith='', username=username).values('borrowed_books__title')
        return render(request,'myapp/myorders.html',{'order_list':order_list})

    else:
        return render(request, 'myapp/myorders.html',{'error':'You are not a registered member!'})


@login_required
def profile(request):
    if request.method=='POST':
        u_form=UserUpdateForm(request.POST,instance=request.user)
        p_form=ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()

            messages.success(request,'Your profile is updated successfully!')
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfileUpdateForm(instance=request.user.profile)
            context = {
                'u_form': u_form,
                'p_form': p_form
            }
            return render(request,'myapp/profile.html',context)

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

        context = {
            'u_form': u_form,
            'p_form': p_form
        }

        return render(request,'myapp/profile.html', context)


def forgot_password(request):
    if request.method=='POST':
        form=PasswordRequestForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            last_name = form.cleaned_data['last_name']
            first_name = form.cleaned_data['first_name']

            lettersAndDigits = string.ascii_letters + string.digits
            random_pass = ''.join(random.choice(lettersAndDigits) for i in range(8))
            user=User.objects.get(last_name=last_name,first_name=first_name)
            user.set_password(random_pass)
            user.save()

            subject="Password Recovery"
            from_email="chandakk@uwindsor.ca"
            to_email=[email]
            msg1="This email is for password recovery. The new password is: "
            msg2=random_pass
            msg3=" You can Log In here: http://127.0.0.1:8000/myapp/user_login/"
            signup_message=msg1+msg2+msg3
            send_mail(subject=subject,from_email=from_email,recipient_list=to_email, message=signup_message, fail_silently=False)

            return render(request, 'myapp/forgot_password_done.html')
        else:
            return render(request, 'myapp/forgot_password.html', {'form': form})

    else:
        form=PasswordRequestForm()
        return render(request,'myapp/forgot_password.html',{'form':form})


@login_required

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Books Management About page{% endblock %}</title>
</head>
<body>
{% block body_block %}
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">About <span class="font-weight-bold">Books Management</span></legend>
    </fieldset>
    <div class="form-group">
        <p>Your lucky number is {{ mynum }}</p>
        <p>Book Management is a web application to access books, keep track of orders, check reviews and many more.</p>
        <p>Technologies used: Python, Django, SQLite, Bootstrap, PyCharm</p>
        <h6>Application contributors:</h6>
        <p>Janki Patel</p>
        <p>Khyati Chandak</p>
        <p>Meera Moradiya</p>
    </div>

    <div class="border-top pt-3">
        <small class="text-muted">
            <a class="ml-2" href="{%  url 'myapp:index' %}">Home page</a>
        </small>
    </div>
{% endblock %}
</body>
</html>

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>eBook App</title>
</head>
<body>

    <h2>This is an eBook APP.</h2>
    <a href="/myapp/">Main page</a>(hardcoded url)<br>
    <a href="{%  url 'myapp:index' %}">Main page</a>(url namespacing)
</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">


    <link rel="stylesheet" type="text/css" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'myapp/books.png' %}">
    <script type="text/javascript" rel="{% static '/js/bootstrap.js' %}"></script>

    <title>{% block title %}Books Management{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-navbar">
  <img class="logo-img" src="{% static 'myapp/books.png' %}">
  <a class="navbar-brand" href="#">Books Management</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'myapp:index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:findbooks' %}">Find Books<span class="sr-only"></span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:place_order' %}">Place Order<span class="sr-only"></span></a>
      </li>
      {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:review' %}">Review Book<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:myorders' %}">My Orders<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'myapp:check_reviews' %}">Check Reviews<span class="sr-only"></span></a>
          </li>
      {% endif %}
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:about' %}">About<span class="sr-only"></span></a>
      </li>

    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET">

        {% csrf_token %}

        {% if user.is_authenticated %}
            <a class="btn btn-light" href="{%  url 'myapp:profile' %}">{{ request.user.username | capfirst}}</a>&nbsp; &nbsp;
            <a class="btn btn-outline-light" href="{%  url 'myapp:user_logout' %}">Logout</a>
        {% else %}
            Hello User &nbsp; &nbsp;
            <a class="btn btn-outline-light my-2 my-sm-0" href="{% url 'myapp:user_login' %}">LogIn</a>&nbsp; &nbsp;
            <a class="btn btn-outline-light" href="{% url 'myapp:user_register' %}">Register</a>
        {% endif %}

    </form>
  </div>
</nav>

    <div role="main" class="container main-body">
        <div class="col-12 col-lg-6 col-xl-6 col-md-6 col-sm-8 col-xs-12 mx-auto">
        <div class="bg-light">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
            {% endif %}
            {% block body_block %}***{% endblock %}
        </div>
        </div>
    </div>

</body>
</html>

myapp/templates/myapp/chk_reviews.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<div class="content-section">
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Book Review</legend>
    </fieldset>
    <div class="form-group">
        <ol>
            {% for book in booklist %}
                <li><a href="{% url 'myapp:check_reviews_done' book.id %}">{{ book.title }}</a></li>
            {% endfor %}
        </ol>

    </div>
</div>

{% endblock %}

myapp/templates/myapp/chk_reviews_done.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<div class="content-section">
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">Book Review</legend>
    </fieldset>
    <div class="form-group">

        {% if avg != 0 %}
            <p>Average book ratings : {{ avg }}</p>
        {% else %}
            <p>No book reviews</p>
        {% endif %}
    </div>
</div>
<div class="border-top pt-3">
    <small class="text-muted">
        Do you want to check more reviews? <a clas="ml-2" href="{% url 'myapp:check_reviews' %}">Check Reviews</a>
    </small>
</div>

{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
    {% if book %}
    <fieldset class="form-group">
         <legend class="border-bottom mb-4">Details of Book <span class="font-weight-bold">{{ book.title }}</span></legend>
    </fieldset>
    <table border="1">
        <tr>
            <th>Title</th>
            <th>Price($)</th>
            <th>Publisher</th>
            <th>Category</th>
            <th>Num pages</th>
            <th>Num reviews</th>
        </tr>
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.publisher.name }}</td>
            <td>{{ book.category }}</td>
            <td>{{ book.num_pages }}</td>
            <td>{{ book.num_reviews }}</td>
        </tr>
    </table>
    {% endif %}
    <br>
    <div class="border-top pt-3">
        <small class="text-muted">
            <p><a href="{% url 'myapp:index' %}">List of books</a></p>
        </small>
    </div>
{% endblock %}

myapp/templates/myapp/detail0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>eBook App</title>
</head>
<body>
{% if book %}
    <table border="1" style="border-collapse: collapse">
    <tr>
        <th>Title</th>
        <th>Price($)</th>
        <th>Publisher</th>
    </tr>
{#    {%  for b in book %}#}
        <tr>
            <td>{{ book.title }}</td>
            <td>{{ book.price }}</td>
            <td>{{ book.publisher.name }}</td>
        </tr>
{#    {% endfor %}#}
    </table>
{% endif %}

<p><a href="{% url 'myapp:index' %}">Main page</a></p>
</body>
</html>

myapp/templates/myapp/forgot_password.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

    <div class="content-section">
         <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Request Password</legend>
                {{ form|crispy }}

             </fieldset>
             <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Request Password</button>
             </div>
         </form>
    </div>

{% endblock %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
{% if booklist %}
    <fieldset class="form-group">
         <legend class="border-bottom mb-4">List of Books</legend>
    </fieldset>
    <div class="form-group">
    <ol>
        {% for book in booklist %}
            <li><a href="{% url 'myapp:detail' book.id %}">{{ book.title }}</a></li>
        {% endfor %}
    </ol>

{% else %}
    <strong>There are no available books!</strong>

{% endif %}

    {% if request.session.username %}
        {% if request.session.last_login  %}
            <p>Last Login : {{ request.session.last_login }}</p>
        {% else %}
            <p>Your last login was more than one hour ago</p>
        {% endif %}
    {% endif %}
    </div>
{% endblock %}

myapp/templates/myapp/logout.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
    <div class="content-section">
    <fieldset class="form-group">
        <legend class="border-bottom mb-4">You have been logged out</legend>
    </fieldset>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a clas="ml-2" href="{% url 'myapp:user_login' %}">Login Again</a>
        </small>
    </div>
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
    <fieldset class="form-group">
         <legend class="border-bottom mb-4">View Order</legend>
    </fieldset>
    <div class="form-group">
        <ul>
        {% if books %}
            {% for book in books %}
                <li>{{ book.title }}</li>
            {% endfor %}
        {% else %}
            <li>No books available with given criteria</li>
        {% endif %}
        </ul>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Place more order? <a clas="ml-2" href="{% url 'myapp:place_order' %}">Order Books</a>
        </small>
    </div>
{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}

     <form action="{% url 'myapp:place_order' %}" method="post">
        {% csrf_token %}
         <fieldset class="form-group">
             <legend class="border-bottom mb-4">Place Order</legend>
             {{ form|crispy }}
         </fieldset>
        <div class="form-group">
            <input type="submit" name="Submit" value="Place Order" class="btn btn-outline-info">
        </div>
    </form>

{% endblock %}

myapp/templates/myapp/profile.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}
    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">

            <div class="media-body">
                <h2 class="account-heading">{{ user.username|capfirst }}</h2>
                <p class="text-secondary">{{ user.email }}</p>
            </div>
        </div>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}
            {{ p_form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
        <div class="border-top pt-3">
            <small class="text-muted">
                <a class="ml-2" href="{% url 'myapp:change_password' %}">Change Password</a>
            </small>
        </div>
    </form>
    </div>
{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
    <div class="content-section">
        <form method="POST">
            {%  csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form | crispy }}
{#                    {{ form.as_p }}#}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already have an Account? <a clas="ml-2" href="{% url 'myapp:user_login' %}">Sign In</a>
            </small>
        </div>
    </div>

{% endblock %}